### ISSUE TITLE
add this helm chart to the cetic repo

### ISSUE THREAD

**Issue by AyadiAmen** [cetic/helm-drupal#1]
This helm chart deploys Drupal in a kubernetes cluster, the official Drupal docker image is used and it can be installed using a Postgresql as well as a Mysql database. can this helm chart be added to the cetic helm repo https://github.com/cetic/helm-charts so that we can use it with FADI ( instead of bitnami's helm chart that doesn't support postgresql databases ) ?

**Comment by alexnuttinck** [comment]
See my PR, it will be done when you push a commit on the master branch.

**Comment by AyadiAmen** [comment]
thank you @alexnuttinck , i merged the PR and there was an error publishing the chart:

```
>> Publishing to gh-pages branch of cetic/helm-charts
On branch gh-pages
Your branch is up to date with 'origin/gh-pages'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   drupal/drupal-0.1.0.tgz
	modified:   index.yaml

[gh-pages f357971] Published by CircleCI https://circleci.com/gh/cetic/helm-drupal/5
 2 files changed, 154 insertions(+), 141 deletions(-)
 create mode 100644 drupal/drupal-0.1.0.tgz
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by alexnuttinck** [comment]
Right, I forgot to add an authenticating key for this repo!

**Comment by alexnuttinck** [comment]
Done @AyadiAmen

**Comment by AyadiAmen** [comment]
@alexnuttinck that was fast! thank you :) i'm closing the issue.
